Repository gisce/powerp-docs, pull requests merged in 2018-05, with the labels that each got.

#313 ADD Checklist extension
  mkdocs.yml
  mkdocs_es.yml
  requirements.txt
Labels: enhancement, interface, to be merged

#315 Imp material interface
  mkdocs.yml
  mkdocs_es.yml
  requirements.txt
Labels: bug, enhancement, interface, to be merged

#316 IMP Material Header colour
  docs/extra/css/site.css
  mkdocs.yml
Labels: enhancement, interface, to be merged

#320 Remove old restriction
  docs/distri/adm-pub/resoluciones/circular_4-2015.md
Labels: enhancement

#321 ADD custom footer block with build time
  custom/main.html
  mkdocs.yml
  mkdocs_es.yml
Labels: enhancement, to be merged
